# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_lockbox_wrappers", use_symbols = TRUE, package_name = "lockbox")

#' @usage NULL
#' @useDynLib lockbox, .registration = TRUE
NULL

#' Decrypt an age-encrypted file using a passphrase
age_decrypt_passphrase <- function(encrypted_file_path, passphrase) .Call(wrap__age_decrypt_passphrase, encrypted_file_path, passphrase)

#' Decrypt an age-encrypted file using a private key
age_decrypt_key <- function(encrypted_file_path, private_key_path) .Call(wrap__age_decrypt_key, encrypted_file_path, private_key_path)


# nolint end
